services:

    php:
        build:
            context: .
            dockerfile: Dockerfile
        restart: unless-stopped
        working_dir: /var/www/html/
        volumes:
           - ./:/var/www/html
        depends_on:
         - mysql

    nginx:
        image: nginx:1.25.5-alpine
        restart: unless-stopped
        volumes:
          - ./:/var/www/html/
          - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
          - ./docker/nginx/logs/:/var/log/nginx/
        ports:
         - 80:80
        depends_on:
         - php


    mysql:
        image: mysql:8.4.0
        restart: unless-stopped
        environment:
         - MYSQL_DATABASE=profile
         - MYSQL_ROOT_PASSWORD=profile
        ports:
         - 3306:3306
        volumes:
         - ./docker/mysql:/var/lib/mysql
