services:

    php:
        build:
            context: ./docker/php/
            dockerfile: Dockerfile
        restart: unless-stopped
        working_dir: /var/www/html/
        volumes:
           - .:/var/www/html
        depends_on:
         - mysql

    nginx:
         build:
            context: ./docker/nginx/
            dockerfile: Dockerfile
         restart: unless-stopped
         volumes:
            - .:/var/www/html
         ports:
         - 80:80
         depends_on:
         - php


    mysql:
        image: mysql:8.4.0
        restart: unless-stopped
        environment:
         - MYSQL_DATABASE=filemanager
         - MYSQL_ROOT_PASSWORD=filemanager
        ports:
         - 3306:3306
        volumes:
         - ./docker/mysql:/var/lib/mysql
